### ISSUE TITLE
weird sorting of CLangd items; 'std::stack' item is lost

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_lsp#173] opened 2023-04-25 21:28 UTC
1) sort order is strage

![Screenshot from 2023-04-26 00-27-13](https://user-images.githubusercontent.com/4154978/234408001-8c78cc08-cb90-4737-b226-0eacfca14532.png)

2) now I cannot find the `std::stack......` item even if I type "st" or "std" ! that item is mentioned in my prev issue #172 

picture of it:
https://user-images.githubusercontent.com/4154978/234407269-9eeba359-896f-46c4-b058-23d0d49780f0.png

**Comment by Alexey-T** [comment] 2023-04-25 21:31
```
user@PC:~$ clangd --version
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

**Comment by veksha** [comment] 2023-04-25 22:01
what if you continue to type.. will it appear?

**Comment by Alexey-T** [comment] 2023-04-25 22:05
yes, it appears later 

![Screenshot from 2023-04-26 01-04-51](https://user-images.githubusercontent.com/4154978/234414715-e32a980c-8c6f-4688-95fd-5c1507c569c0.png)

**Comment by veksha** [comment] 2023-04-25 22:06
without `#include <stack>` i cannot see `stack` at all

**Comment by Alexey-T** [comment] 2023-04-25 22:08
more correct file. still cannot find 'std::stack' in the whole list!
```
#include <stdio.h>
#include <stack>
enum eState { stateOn, stateOff };
int main(){
  st
    
}
```

**Comment by Alexey-T** [comment] 2023-04-25 22:09
I guess you can do nothing with std::stack.
can you sort items? so "std::....." show together?

**Comment by veksha** [comment] 2023-04-25 22:10
can't reproduce.
![image](https://user-images.githubusercontent.com/275333/234415449-d2357aa3-b2d7-4049-9d0d-82855712ff01.png)

**Comment by Alexey-T** [comment] 2023-04-25 22:12
you dont see this weird sorting?

![Screenshot from 2023-04-26 01-11-59](https://user-images.githubusercontent.com/4154978/234415693-97018690-f7d7-470d-8cbc-7b463bbf2a21.png)

**Comment by veksha** [comment] 2023-04-25 22:18
try this, better?

```diff
diff --git a/language.py b/language.py
index e89b29d..3148fe1 100644
--- a/language.py
+++ b/language.py
@@ -1781,7 +1781,8 @@ class CompletionMan:
             return s2.lower() in s1.lower()
     
     def sort(self, item, word):
-        s1 = item.get('filterText', item['label'].strip())
+        #s1 = item.get('filterText', item['label'].strip())
+        s1 = item['label'].strip()
         s2 = word
         pos_bracket = s1.find('(')
         s1 = s1 if pos_bracket == -1 else s1[:pos_bracket]

```

**Comment by veksha** [comment] 2023-04-25 22:22
keep in mind that clangd is not giving full list all the time (i think it's optimization)
for "st" i get 98 results (list marked as incomplete, caching will not be used)
for "std" i get only 4 results! (list marked as complete)

with `LOG_CACHE = True`:
```
using fresh results. items: 98  incomplete: True
using fresh results. items: 4  incomplete: False
```

**Comment by veksha** [comment] 2023-04-25 22:26
even better strip this bullet!
`s1 = item['label'].strip().strip('•')`

**Comment by Alexey-T** [comment] 2023-04-25 22:36
yes,now much better sorting.

**Comment by Alexey-T** [comment] 2023-04-25 22:38
`.strip().strip('•')` can it be replaced with single strip (with 1 param)?

**Comment by veksha** [comment] 2023-04-25 22:47
try `.strip(' •')`

**Comment by Alexey-T** [comment] 2023-04-26 06:48
it's final patch, `item.get('filterText'` not needed now?

**Comment by veksha** [comment] 2023-04-26 12:40
no (in `def sort`)

**Comment by Alexey-T** [comment] 2023-04-26 12:42
No to “it’s final patch”. Waiting for final

**Closed** 2023-04-26 13:11 UTC
